<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.0 /home/devit/Code/3dtesting/static/models/bocciolo_metallic.glb --root /models/ --types --printwidth 120 --precision 2
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()
  export let castShadow:boolean = false
  type GLTFResult = {
    nodes: {
      Cone: THREE.Mesh
      Sphere: THREE.Mesh
    }
    materials: {
      ['Materiale.001']: THREE.MeshStandardMaterial
      Materiale: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/models/bocciolo_metallic.glb',{
    useDraco: true
  })

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh geometry={gltf.nodes.Cone.geometry} material={gltf.materials['Materiale.001']} position={[0, 2, -0.8]} {castShadow}/>
    <T.Mesh geometry={gltf.nodes.Sphere.geometry} material={gltf.materials.Materiale} {castShadow}/>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
