<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.0 /home/devit/Code/3dtesting/static/models/ramo_01_rotto_animaz.glb --root /models/ --types --printwidth 120 --precision 2
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { useGltf, useGltfAnimations } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()
  export let castShadow:boolean = false
  export let receiveShadow:boolean = false

  type ActionName = 'ArmaturaAction'
  type GLTFResult = {
    nodes: {
      Sfera003: THREE.SkinnedMesh
      Bone: THREE.Bone
      Bone002: THREE.Bone
      Bone006: THREE.Bone
    }
    materials: {
      ['Frensel Pattern 01']: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/models/ramo_01_rotto_animaz.glb')
  export const { actions, mixer } = useGltfAnimations<ActionName>(gltf, ref)
  $:$actions.ArmaturaAction?.play()
  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group name="Scene">
      <T.Group name="Armatura" position={[0.36, 0.42, 0.03]} rotation={[0, 0, 0.74]} scale={0.56}>
        <T is={gltf.nodes.Bone} />
        <T is={gltf.nodes.Bone002} />
        <T is={gltf.nodes.Bone006} />
        <T.SkinnedMesh
          name="Sfera003"
          geometry={gltf.nodes.Sfera003.geometry}
          material={gltf.materials['Frensel Pattern 01']}
          skeleton={gltf.nodes.Sfera003.skeleton}
          {castShadow}
          {receiveShadow}
        />
      </T.Group>
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
